data_p32data_me_mo_q_re_dl<-function(data_p3,length_all,p_cut=5e-8,adj_m="none",trace=F){
  se<-eff<-eff_indiv<-NULL
  loc<-which(p.adjust(data_p3$wald_p,adj_m)<p_cut)
  cor_correct<-T
  for(i in 1:length(loc)){
    fit1<-dl_nohp(est_mkp=c(data_p3$m_hat[loc[i],],data_p3$k_hat[loc[i],]),
                  vcov_mkp=NULL,mkp_indiv=data_p3$mkp_ind_list[[loc[i]]],name=rownames(data_p3$m_hat)[loc[i]],
                  nonNA_loc=data_p3$nonNA_loc_list[[loc[i]]],length_all=length_all)
    if(cor_correct){
      eff_indiv<-cbind(eff_indiv,fit1$est_indiv)
    }
    se<-cbind(se,fit1$se)
    eff<-cbind(eff,fit1$est)
    if(trace){my_moni("SNP",i,length(loc))}
  }
  colnames(se)<-colnames(eff)<-rownames(data_p3$m_hat)[loc]
  if(!is.null(eff_indiv)){
    colnames(eff_indiv)<-rownames(data_p3$m_hat)[loc]
  }
  return(list(eff=eff,se=se,eff_indiv=eff_indiv))
}
