meta_eff2<-function(eff,vcov,eff_indiv=NULL){
  if(anyNA(eff)|anyNA(vcov)){
    return(list(eff_m=NA,se_m=NA,eff_m_indiv=NA,w=rep(NA,length(eff))))
  }
  s<-solve(vcov)
  k<-colSums(s)/sum(s)
  eff_m<-t(k)%*%eff
  if(!is.null(eff_indiv)){
    eff_m_indiv<-eff_indiv%*%k
  }else{
    eff_m_indiv<-NA
  }
  se_m<-sqrt(t(k)%*%vcov%*%k)
  return(list(eff_m=eff_m[1,1],se_m=se_m[1,1],eff_m_indiv=eff_m_indiv,w=k))
}
