myselect<-function(x,loc,type=c("c","r")){
  if(is.logical(loc)){stop("Logical loc in myselect.")}
  if(is.null(x)){return(NULL)}
  type<-match.arg(type)
  if(type=="c"){
    if(nrow(x)==1){
      out<-rbind(x[,loc])
      rownames(out)<-rownames(x)
      colnames(out)<-colnames(x)[loc]
      return(out)
    }
    out<-cbind(x[,loc])
    rownames(out)<-rownames(x)
    colnames(out)<-colnames(x)[loc]
    return(out)
  }
  if(type=="r"){
    if(ncol(x)==1){
      out<-cbind(x[loc,])
      rownames(out)<-rownames(x)[loc]
      colnames(out)<-colnames(x)
      return(out)
    }  
    out<-rbind(x[loc,])
    rownames(out)<-rownames(x)[loc]
    colnames(out)<-colnames(x)
    return(out)
  }
}

