# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f_est_k_prior_loop <- function(k_matr, s_list, ss_list, mychisq, p0_sp, p0, p_cut, u1, u2, sigma) {
    .Call(`_MRprollim_f_est_k_prior_loop`, k_matr, s_list, ss_list, mychisq, p0_sp, p0, p_cut, u1, u2, sigma)
}

loop_p3_1 <- function(p1_sp, p2_sp, b1, u1, u2, p1, p2, s_h, m_matrix, post_sample_k1, post_sample_k2, f1_matr, f2_matr, sigma_prime_list, sign_k1, sign_k2) {
    .Call(`_MRprollim_loop_p3_1`, p1_sp, p2_sp, b1, u1, u2, p1, p2, s_h, m_matrix, post_sample_k1, post_sample_k2, f1_matr, f2_matr, sigma_prime_list, sign_k1, sign_k2)
}

loop_p3_1_indiv_p <- function(p1_sp, p2_sp, b1, u1, u2, p1, p2, s_h, m_matrix, post_sample_k1, post_sample_k2, f1_matr, f2_matr, sigma_prime_list, sign_k1, sign_k2) {
    .Call(`_MRprollim_loop_p3_1_indiv_p`, p1_sp, p2_sp, b1, u1, u2, p1, p2, s_h, m_matrix, post_sample_k1, post_sample_k2, f1_matr, f2_matr, sigma_prime_list, sign_k1, sign_k2)
}

loop_p3_1_bi <- function(p1_sp, p2_sp, b1_t, u1, u2, p1, p2, log_appr, m_matrix, s_h, post_sample_k1, post_sample_k1_exp1, post_sample_k2, post_sample_k2_exp1, post_sample_p, g1_matr, g2_matr, sigma_prime_list, sign_k1, sign_k2) {
    .Call(`_MRprollim_loop_p3_1_bi`, p1_sp, p2_sp, b1_t, u1, u2, p1, p2, log_appr, m_matrix, s_h, post_sample_k1, post_sample_k1_exp1, post_sample_k2, post_sample_k2_exp1, post_sample_p, g1_matr, g2_matr, sigma_prime_list, sign_k1, sign_k2)
}

loop_p3_1_bi_indiv_p <- function(p1_sp, p2_sp, b1_t, u1, u2, p1, p2, log_appr, m_matrix, s_h, post_sample_k1, post_sample_k1_exp1, post_sample_k2, post_sample_k2_exp1, post_sample_p, g1_matr, g2_matr, sigma_prime_list, sign_k1, sign_k2) {
    .Call(`_MRprollim_loop_p3_1_bi_indiv_p`, p1_sp, p2_sp, b1_t, u1, u2, p1, p2, log_appr, m_matrix, s_h, post_sample_k1, post_sample_k1_exp1, post_sample_k2, post_sample_k2_exp1, post_sample_p, g1_matr, g2_matr, sigma_prime_list, sign_k1, sign_k2)
}

my_allocate_cpp2 <- function(x, y) {
    .Call(`_MRprollim_my_allocate_cpp2`, x, y)
}

my_calcu_vcov <- function(x_c, y) {
    .Call(`_MRprollim_my_calcu_vcov`, x_c, y)
}

